*** Variables ***
${SUPPLIER_INVOICE}  {"claimId":null,"claimTypeId":12,"claimTypeDesc":"Supplier Invoice","claimStatusId":0,"onHold":null,"onHoldDate":null,"claimStatusDesc":null,"created":null,"billCycleId":null,"claimDateStart":"2025-04-04","claimDateTo":null,"claimantId":4645,"claimantName":"Kylie Magenta","authorityId":null,"divisionId":null,"departmentId":184,"claimDivisionId":1141,"departmentName":"Australia","supplierId":18320,"supplierCode":"NAKAMA","abn":null,"payTo":"Nakama","reference":null,"invoiceNo":"invoice testing","dueDate":"","name":"Supplier Invoice","linkClaimIds":null,"taxFlag":"e","disputedTotal":0,"personalTotal":0,"expenseTotal":0,"workflowId":1574,"stepNo":null,"completedOn":null,"completePurchaseOrder":false,"requiresPurchaseOrder":false,"purchaseNo":null,"cancelDate":null,"importId":null,"exportId":null,"exportRef":null,"expenses":[],"steps":[],"notes":[],"fields":[],"forwardBalance":0,"newBalance":0,"newCredits":0,"invoiceScanning":false,"paymentInfoAcknowledged":false,"cardId":null,"linkClaimMarkedForClose":false,"cardStatus":null,"scheduledFreezeOn":null,"payByCheque":"Y","accountName":"","accountBsb":"","accountNo":"","bpayReference":null,"bpayBiller":null,"variance":null,"allowAcknowledgePaymentInfoMismatch":false,"externalBillLink":null,"approvalComment":null,"approverAcknowledged":null,"source":null,"purchaseOrder":{"deliveryDate":null,"deliveryAddr1":null,"deliveryAddr2":null,"deliveryAddr3":null,"country":null,"contactCompany":null,"contactName":null,"contactPhone":null,"deliveryInstructions":null,"showAmounts":"y","emailPO":false,"emailTo":""},"cardOrder":{"cardOrderId":null,"companyId":null,"claimId":null,"cardholderPhone":null,"orderIssuedOn":null,"orderIssuedBy":null,"cardEndDate":null,"status":null,"cardOrderStatus":null,"deliveryEstimate":null,"trackingUrl":null,"lifetimeLimitAmount":null,"transactionLimitAmount":null,"dailyLimitAmount":null,"monthlyLimitAmount":null,"billingAddress":{"address1":null,"address2":null,"city":null,"state":null,"postCode":null,"countryCode":null},"rules":[],"cardLabel":null,"validationStatus":null,"validationReason":null,"embossedName":null},"invoiceApprovalOption":"GO_THROUGH_APPROVAL","supplierValidationAcknowledged":false}

${SUPPLIER_INVOICE_JSON}
...    {
...      "claimId": null,
...      "claimTypeId": 12,
...      "claimTypeDesc": "Supplier Invoice",
...      "claimStatusId": 0,
...      "onHold": null,
...      "onHoldDate": null,
...      "claimStatusDesc": null,
...      "created": null,
...      "billCycleId": null,
...      "claimDateStart": "2025-04-04",
...      "claimDateTo": null,
...      "claimantId": 4645,
...      "claimantName": "Kylie Magenta",
...      "authorityId": null,
...      "divisionId": null,
...      "departmentId": 184,
...      "claimDivisionId": 1141,
...      "departmentName": "Australia",
...      "supplierId": 18320,
...      "supplierCode": "NAKAMA",
...      "abn": null,
...      "payTo": "Nakama",
...      "reference": null,
...      "invoiceNo": "INVOICE_PLACEHOLDER",
...      "dueDate": "",
...      "name": "Supplier Invoice",
...      "linkClaimIds": null,
...      "taxFlag": "e",
...      "disputedTotal": 0,
...      "personalTotal": 0,
...      "expenseTotal": 0,
...      "workflowId": 1574,
...      "stepNo": null,
...      "completedOn": null,
...      "completePurchaseOrder": false,
...      "requiresPurchaseOrder": false,
...      "purchaseNo": null,
...      "cancelDate": null,
...      "importId": null,
...      "exportId": null,
...      "exportRef": null,
...      "expenses": [],
...      "steps": [],
...      "notes": [],
...      "fields": [],
...      "forwardBalance": 0,
...      "newBalance": 0,
...      "newCredits": 0,
...      "invoiceScanning": false,
...      "paymentInfoAcknowledged": false,
...      "cardId": null,
...      "linkClaimMarkedForClose": false,
...      "cardStatus": null,
...      "scheduledFreezeOn": null,
...      "payByCheque": "Y",
...      "accountName": "",
...      "accountBsb": "",
...      "accountNo": "",
...      "bpayReference": null,
...      "bpayBiller": null,
...      "variance": null,
...      "allowAcknowledgePaymentInfoMismatch": false,
...      "externalBillLink": null,
...      "approvalComment": null,
...      "approverAcknowledged": null,
...      "source": null,
...      "purchaseOrder": {
...        "deliveryDate": null,
...        "deliveryAddr1": null,
...        "deliveryAddr2": null,
...        "deliveryAddr3": null,
...        "country": null,
...        "contactCompany": null,
...        "contactName": null,
...        "contactPhone": null,
...        "deliveryInstructions": null,
...        "showAmounts": "y",
...        "emailPO": false,
...        "emailTo": ""
...      },
...      "cardOrder": {
...        "cardOrderId": null,
...        "companyId": null,
...        "claimId": null,
...        "cardholderPhone": null,
...        "orderIssuedOn": null,
...        "orderIssuedBy": null,
...        "cardEndDate": null,
...        "status": null,
...        "cardOrderStatus": null,
...        "deliveryEstimate": null,
...        "trackingUrl": null,
...        "lifetimeLimitAmount": null,
...        "transactionLimitAmount": null,
...        "dailyLimitAmount": null,
...        "monthlyLimitAmount": null,
...        "billingAddress": {
...          "address1": null,
...          "address2": null,
...          "city": null,
...          "state": null,
...          "postCode": null,
...          "countryCode": null
...        },
...        "rules": [],
...        "cardLabel": null,
...        "validationStatus": null,
...        "validationReason": null,
...        "embossedName": null
...      },
...      "invoiceApprovalOption": "GO_THROUGH_APPROVAL",
...      "supplierValidationAcknowledged": false
...    }
