*** Variables ***
${RANDON_INVOICE_NUMBER}    Evaluate    "Text_automation-" + str(random.randint(1000, 9999))  random

${CLALIM_INVOICE}=    Create Dictionary
...    abn=${NONE}
...    accountBsb=${EMPTY}
...    accountName=${EMPTY}
...    accountNo=${EMPTY}
...    allowAcknowledgePaymentInfoMismatch=${FALSE}
...    approvalComment=${NONE}
...    approverAcknowledged=${NONE}
...    authorityId=${NONE}
...    billCycleId=${NONE}
...    bpayBiller=${NONE}
...    bpayReference=${NONE}
...    cancelDate=${NONE}
...    cardId=${NONE}
...    cardOrder=    Create Dictionary    cardOrderId=${NONE}    companyId=${NONE}    claimId=${NONE}    cardholderPhone=${NONE}    orderIssuedOn=${NONE}
...    cardStatus=${NONE}
...    claimDateStart=2025-04-04
...    claimDateTo=${NONE}
...    claimDivisionId=1141
...    claimId=${NONE}
...    claimStatusDesc=${NONE}
...    claimStatusId=0
...    claimTypeDesc=Supplier Invoice
...    claimTypeId=12
...    claimantId=4645
...    claimantName=Kylie Magenta
...    completePurchaseOrder=${FALSE}
...    completedOn=${NONE}
...    created=${NONE}
...    departmentId=184
...    departmentName=Australia
...    disputedTotal=0
...    divisionId=${NONE}
...    dueDate=${EMPTY}
...    expenseTotal=0
...    expenses=${EMPTY}
...    exportId=${NONE}
...    exportRef=${NONE}
...    externalBillLink=${NONE}
...    fields=${EMPTY}
...    forwardBalance=0
...    importId=${NONE}
...    invoiceApprovalOption=GO_THROUGH_APPROVAL
...    invoiceNo=${RANDON_INVOICE_NUMBER}
...    invoiceScanning=${FALSE}
...    linkClaimIds=${NONE}
...    linkClaimMarkedForClose=${FALSE}
...    name=Supplier Invoice
...    newBalance=0
...    newCredits=0
...    notes=${EMPTY}
...    onHold=${NONE}
...    onHoldDate=${NONE}
...    payByCheque=Y
...    payTo=Nakama
...    paymentInfoAcknowledged=${FALSE}
...    personalTotal=0
...    purchaseNo=${NONE}
...    purchaseOrder=    Create Dictionary    deliveryDate=${NONE}    deliveryAddr1=${NONE}    deliveryAddr2=${NONE}    deliveryAddr3=${NONE}    country=${NONE}
...    contactCompany=${NONE}
...    contactName=${NONE}
...    contactPhone=${NONE}
...    country=${NONE}
...    deliveryAddr1=${NONE}
...    deliveryAddr2=${NONE}
...    deliveryAddr3=${NONE}
...    deliveryDate=${NONE}
...    deliveryInstructions=${NONE}
...    emailPO=${FALSE}
...    emailTo=${EMPTY}
...    showAmounts=y
...    reference=${NONE}
...    requiresPurchaseOrder=${FALSE}
...    scheduledFreezeOn=${NONE}
...    source=${NONE}
...    stepNo=${NONE}
...    steps=${EMPTY}
...    supplierCode=NAKAMA
...    supplierId=18320
...    supplierValidationAcknowledged=${FALSE}
...    taxFlag=e
...    variance=${NONE}
...    workflowId=1574
